In [1]:
import torch
import numpy as np

In [2]:
list_1 = [[3,2,1],[4,5,6]]
arr_1 = np.array(list_1)
tr_1 = torch.FloatTensor(list_1)

In [3]:
print(type(arr_1),' : ' ,arr_1)
print(type(tr_1),' : ' ,tr_1)

<class 'numpy.ndarray'>  :  [[3 2 1]
 [4 5 6]]
<class 'torch.FloatTensor'>  :  
 3  2  1
 4  5  6
[torch.FloatTensor of size 2x3]



In [4]:
from torch.autograd import Variable

In [5]:
var_1 = Variable(tr_1, requires_grad=True)
print(var_1)

Variable containing:
 3  2  1
 4  5  6
[torch.FloatTensor of size 2x3]



In [6]:
v_out = torch.mean(var_1*var_1)
print(v_out)

Variable containing:
 15.1667
[torch.FloatTensor of size 1]



In [7]:
v_out.backward()
print(var_1.grad)

Variable containing:
 1.0000  0.6667  0.3333
 1.3333  1.6667  2.0000
[torch.FloatTensor of size 2x3]



In [8]:
print(var_1.data)
print(var_1.data.numpy())


 3  2  1
 4  5  6
[torch.FloatTensor of size 2x3]

[[3. 2. 1.]
 [4. 5. 6.]]


In [11]:
var_1.size(0)

2