In [2]:
import tensorflow as tf
import numpy as np

In [2]:
# build constant
ts_c = tf.constant(2, name='ts_c')
ts_x = tf.Variable(ts_c+5, name='ts_x')

# Execute 
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    # initialize all variable in tensorflow 
    sess.run(init)
    print('ts_c=', sess.run(ts_c))
    print('ts_x=', sess.run(ts_x))
    print('ts_x', ts_x.eval(session=sess)) #use eval() to show variable
    
# if without using "with" syntax, need close sess by "sess.close()"

ts_c= 2
ts_x= 7
ts_x 7


In [3]:
# placeholder：give the  value when executing

width = tf.placeholder("int32")
height = tf.placeholder("int32")
area = tf.multiply(width, height)

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=', sess.run(area, feed_dict={width:6, height:8}))

area= 48


In [4]:
# build one dimension tensor
ts_x = tf.Variable([0.4, 0.2, 0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_x)
    print(X)

[ 0.40000001  0.2         0.40000001]


In [14]:
# build two dimension tensor
ts_x = tf.Variable([[0.4, 0.2, 0.4]]) #[[]] two parentheses mean 2-d

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_x)
    print(X)
X.shape

[[ 0.40000001  0.2         0.40000001]]


(1, 3)

In [5]:
# matmul
X = tf.Variable([[1., 1., 1.]])
W = tf.Variable([ [-0.5, -0.2],
                  [-0.3,  0.4],
                  [-0.5, 0.2]])
b = tf.Variable([[0.1, 0.2]])

XW = tf.matmul(X,W) + b

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

[[-1.19999993  0.60000002]]


In [13]:

with tf.Session() as sess:
    tens1 = tf.constant([[[1,2],[2,3],[3,4],[5,6]]])
    print(sess.run(tens1)[0,1,0])
    


2
